# From https://medium.com/team-rockstars-it/the-easiest-way-to-build-a-flutter-ios-app-using-github-actions-plus-a-key-takeaway-for-developers-48cf2ad7c72a
name: "Build IPA Package"
on: [push, pull_request]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install your project's dependencies
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios
      
      - name: Flutter build
        run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - run: zip -qq -r -9 PrescoreFLutter.ipa Payload
        working-directory: build/ios/iphoneos
          
      # Collect the file and upload as artifact         
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v3
        with:
         name: release-ipa
         # Path to the release files
         path: build/ios/iphoneos/*.ipa
         
