name: Build Android apk and bundle
on: [push, pull_request]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle

      - uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - uses: actions/upload-artifact@v2
        with:
          name: Signed apk
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          
      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          args: '--acl public-read --follow-symlinks'
          # aws key id
          aws_key_id: ${{ secrets.COS_SECRET_ID }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.COS_SECRET_KEY }}
          aws_s3_endpoint: 'cos.ap-beijing.myqcloud.com'
          # aws bucket name
          aws_bucket: 'app-dist-1307054264'
          # directory to upload
          source_dir: build/app/outputs/apk/release
          # destination directory for upload
          destination_dir: /actions/prescore_flutter/${{ github.run_number }}
