name: Build Android apk and bundle
on: [push, pull_request]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.4.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run cronet:setup
      - run: flutter build apk
      - run: flutter build appbundle
      
      - run: zip -d build/app/outputs/bundle/release/app-release.aab META-INF/\*

      - uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - run: rm build/app/outputs/apk/release/signingKey.jks
      
      - uses: r0adkll/sign-android-release@v1
        id: sign_aab
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - run: rm build/app/outputs/bundle/release/signingKey.jks

      - uses: actions/upload-artifact@v3
        with:
          name: Signed apk
          path: |
            ${{steps.sign_apk.outputs.signedReleaseFile}}
            ${{steps.sign_aab.outputs.signedReleaseFile}}
          
      - name: Upload COS APK
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--acl public-read --follow-symlinks'
        env:
          AWS_S3_BUCKET: 'app-dist-1307054264'
          AWS_ACCESS_KEY_ID: ${{ secrets.COS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_KEY }}
          AWS_S3_ENDPOINT: 'https://cos.ap-beijing.myqcloud.com/'
          SOURCE_DIR: 'build/app/outputs/apk/release' 
          DEST_DIR: 'actions/prescore_flutter/${{ github.run_number }}/apk'
          
      - name: Upload COS AAB
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--acl public-read --follow-symlinks'
        env:
          AWS_S3_BUCKET: 'app-dist-1307054264'
          AWS_ACCESS_KEY_ID: ${{ secrets.COS_SECRET_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_KEY }}
          AWS_S3_ENDPOINT: 'https://cos.ap-beijing.myqcloud.com/'
          SOURCE_DIR: 'build/app/outputs/bundle/release' 
          DEST_DIR: 'actions/prescore_flutter/${{ github.run_number }}/aab'
